![SHU](https://drive.google.com/uc?export=view&id=1oauWClN3B2tjg1AeVHtfjAXZg13d9HXL)

#**Modelling Mechanics of Sports Engineering**
##Week 3
###Session 3 - Practice tasks


<a target="_blank" href="https://github.com/DrJohnKelley/MechanicsPython">
  <img alt="Link to GitHub" src="https://img.shields.io/badge/link_to-GitHub_repo-blue?logo=github&labelColor=black">

</a><a target="_blank" href="https://shuspace.shu.ac.uk/ultra/courses/_350614_1/outline">
  <img alt="Access course folder" src="https://img.shields.io/badge/access_course_files-Folder-yellow">
</a>

#Introduction
This notebook contains practice tasks for **data analysis and visualization**

âœ… **Note: Make sure the AI assistant is turned off**

*Tools> Settings> AI assistance> Hide generative AI features*

#120 years of Olympic history: athletes and results

This is a historical dataset on the modern Olympic Games, including all the Games from Athens 1896 to Rio 2016.

Note that the Winter and Summer Games were held in the same year up until 1992. After that, they staggered them such that Winter Games occur on a four year cycle starting with 1994, then Summer in 1996, then Winter in 1998, and so on. A common mistake people make when analyzing this data is to assume that the Summer and Winter Games have always been staggered.

The file is available on the following public drive link. It has been imported in this notebook for your ease.


</a><a target="_blank" href="https://drive.google.com/file/d/18flGuhE2rfisV6PlA5826p189jVbPr6b/view?usp=drive_link">
  <img alt="Access csv file" src="https://img.shields.io/badge/access_csv_file-Drive_link-yellow">
</a>

Have a look at the data and do some Exploratory Data Analysis (EDA). See what information you can find.

Some examples have been added below to start off with.

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
drive_link = 'https://drive.google.com/file/d/18flGuhE2rfisV6PlA5826p189jVbPr6b/view?usp=drive_link'
url='https://drive.google.com/uc?id=' + drive_link.split('/')[-2]
df = pd.read_csv(url)

df.head()

,ID,Name,Sex,Age,Height,Weight,Team,NOC,Games,Year,Season,City,Sport,Event,Medal
0,1,A Dijiang,M,24.0,180.0,80.0,China,CHN,1992 Summer,1992,Summer,Barcelona,Basketball,Basketball Men's Basketball,NaN
1,2,A Lamusi,M,23.0,170.0,60.0,China,CHN,2012 Summer,2012,Summer,London,Judo,Judo Men's Extra-Lightweight,NaN
2,3,Gunnar Nielsen Aaby,M,24.0,NaN,NaN,Denmark,DEN,1920 Summer,1920,Summer,Antwerpen,Football,Football Men's Football,NaN
3,4,Edgar Lindenau Aabye,M,34.0,NaN,NaN,Denmark/Sweden,DEN,1900 Summer,1900,Summer,Paris,Tug-Of-War,Tug-Of-War Men's Tug-Of-War,Gold
4,5,Christine Jacoba Aaftink,F,21.0,185.0,82.0,Netherlands,NED,1988 Winter,1988,Winter,Calgary,Speed Skating,Speed Skating Women's 500 metres,NaN

In [ ]:
df.info(verbose=True)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 271116 entries, 0 to 271115
Data columns (total 15 columns):
 #   Column  Non-Null Count   Dtype
---  ------  --------------   -----
 0   ID      271116 non-null  int64
 1   Name    271116 non-null  object
 2   Sex     271116 non-null  object
 3   Age     261642 non-null  float64
 4   Height  210945 non-null  float64
 5   Weight  208241 non-null  float64
 6   Team    271116 non-null  object
 7   NOC     271116 non-null  object
 8   Games   271116 non-null  object
 9   Year    271116 non-null  int64
 10  Season  271116 non-null  object
 11  City    271116 non-null  object
 12  Sport   271116 non-null  object
 13  Event   271116 non-null  object
 14  Medal   39783 non-null   object
dtypes: float64(3), int64(2), object(10)
memory usage: 31.0+ MB

###Exercise: 1
Plot number of Events, Nations and Athletes over time

In [ ]:
# Exercise 1
# Write your code here

###Exercise: 2
Plot number of male and female Olympians over time

In [ ]:
# Exercise 2
# Write your code here

##Exercise: 3
Based on the highest number of medals - display the gold, bronze and silver medals count for top 20 Nations

In [ ]:
# Exercise 3
# Write your code here

#What else can you find?

Feel free to look at the notebooks created by contributors on Kaggle for ideas.

</a><a target="_blank" href="https://www.kaggle.com/datasets/heesoo37/120-years-of-olympic-history-athletes-and-results/code">
  <img alt="Kaggle link" src="https://img.shields.io/badge/kaggle-link-blue">
</a>

In [ ]:
# Write code here